### ISSUE TITLE
“mark as successful after x minutes” function is not working properly

### ISSUE THREAD

**Issue by mmuller** [instedd/verboice#616]
Found in version 2.3.9-11-g774be02

Preconditions: 
The Call Flow 'Foo' is the call flow used for incoming calls in the channel 'Bar'
The Call Flow 'Foo' includes a 'Forward Call' step

Steps:
Go to edit the 'Forward Call' step
Check 'mark as successful after x minutes'
Fill the field with '1 minute'
Save the call flow
Call to the channel 'Bar'

Obtained:
The call is forwarded properly
The call is not marked as successful after 1 minute

Expected:
The call should be marked as successful after 1 minute

![screen shot 2014-12-19 at 3 25 41 pm](https://cloud.githubusercontent.com/assets/518152/5509242/bce2d984-8794-11e4-924c-ec889c006e2e.png)
![screen shot 2014-12-19 at 3 25 51 pm](https://cloud.githubusercontent.com/assets/518152/5509243/bce71a8a-8794-11e4-98f8-6cd1e58c9620.png)

**Comment by romeroadrian** [comment]
This feature seems to be working fine.

The calling user must hangup the call after the specified duration during the forwarding stage to mark the call as completed.

In this particular case, a non related error was raised in the flow, causing the call to be marked as failed.

**Comment by nditada** [comment]
@pmallol Can you try to verify this? It doesn't seem that it's fixed.

Test cases would be:
1) Anna calls Verboice, Anna goes through a "mark as succces...after 10 seconds" and gets forwarded to Bob, Bob hang-ups on Anna after 15 seconds. Expected: Call is marked as successful 

2) Anna calls Verboice, Anna goes through a "mark as succces...after 10 seconds" and gets forwarded to Bob, Anna hang-ups on Bob after 15 seconds. Expected: Call is marked as successful 

3) Anna calls Verboice, Anna goes through a "mark as succces...after 10 seconds" and gets forwarded to Bob, Bob hang-ups on Anna after 5 seconds. Expected: Call is marked as failed 

4) Anna calls Verboice, Anna goes through a "mark as succces...after 10 seconds" and gets forwarded to Bob, Anna hang-ups on Bob after 5 seconds. Expected: Call is marked as failed

**Comment by nditada** [comment]
@edjez if you have a link to a call log that had issues, please send it over.

**Comment by pmallol** [comment]
Both cases 1) and 4) work as expected: 1) is marked as successful and 4) as failed.

However, cases number 2) and 3) work the opposite way. 2) is marked as failed and 3) as successful.

**Comment by romeroadrian** [comment]
@nditada case number 3 is marked as successful, since Bob is the one that hang-ups on Anna. In this case, the forward step is 'done' and the call flow is resumed.

**Comment by romeroadrian** [comment]
Case 2 should be fixed

**Comment by pmallol** [comment]
Case 2 still shows up as "failed (fatal error)".
http://poirot-stg.instedd.org/activities/32a85b57-a7b3-443c-8cfb-c33638047db5

**Comment by pmallol** [comment]
Case 2 now shows up as 'completed', as expected.
Working ok in version 2.4.5-pre2

Call log #11991 http://poirot-stg.instedd.org/activities/5a45dd4d-3426-4b16-9cad-ac01011b1774
